# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

R_approx_binomial_car <- function(nnbs, nbs, tau, d, y, n_y, u, mu, use_mu, initial_mode, max_iter, conv_tol, reorder, ratio_correction) {
    .Call('_smccar_R_approx_binomial_car', PACKAGE = 'smccar', nnbs, nbs, tau, d, y, n_y, u, mu, use_mu, initial_mode, max_iter, conv_tol, reorder, ratio_correction)
}

R_bsf_binomial_car <- function(nnbs, nbs, tau, d, y, n_y, u, mu, use_mu, n_particles, seed, reorder, ess_threshold) {
    .Call('_smccar_R_bsf_binomial_car', PACKAGE = 'smccar', nnbs, nbs, tau, d, y, n_y, u, mu, use_mu, n_particles, seed, reorder, ess_threshold)
}

R_amcmc_binomial_car <- function(nnbs, nbs, tau, d, y, n_y, u, mu, use_mu, n_iter, n_burnin, initial_theta, initial_mode, S, max_iter, conv_tol, seed, ratio_correction, reorder) {
    .Call('_smccar_R_amcmc_binomial_car', PACKAGE = 'smccar', nnbs, nbs, tau, d, y, n_y, u, mu, use_mu, n_iter, n_burnin, initial_theta, initial_mode, S, max_iter, conv_tol, seed, ratio_correction, reorder)
}

R_mcmc_binomial_car <- function(nnbs, nbs, tau, d, y, n_y, u, mu, use_mu, n_iter, n_burnin, initial_theta, initial_mode, S, max_iter, conv_tol, seed, n_particles, reorder, ess_threshold) {
    .Call('_smccar_R_mcmc_binomial_car', PACKAGE = 'smccar', nnbs, nbs, tau, d, y, n_y, u, mu, use_mu, n_iter, n_burnin, initial_theta, initial_mode, S, max_iter, conv_tol, seed, n_particles, reorder, ess_threshold)
}

R_print_graph <- function(nnbs, nbs) {
    invisible(.Call('_smccar_R_print_graph', PACKAGE = 'smccar', nnbs, nbs))
}

R_car_Q <- function(nnbs, nbs, tau, d) {
    .Call('_smccar_R_car_Q', PACKAGE = 'smccar', nnbs, nbs, tau, d)
}

R_psi_binomial_car <- function(nnbs, nbs, tau, d, y, n_y, u, mu, use_mu, n_particles, initial_mode, max_iter, conv_tol, seed, reorder, ess_threshold) {
    .Call('_smccar_R_psi_binomial_car', PACKAGE = 'smccar', nnbs, nbs, tau, d, y, n_y, u, mu, use_mu, n_particles, initial_mode, max_iter, conv_tol, seed, reorder, ess_threshold)
}

